// <auto-generated />
namespace HCCSManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class NullableDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201401152213199_NullableDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
