//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCCSManager.WorkdayHCCS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load", ConfigurationName="WorkdayHCCS.ReportPort")]
    public interface ReportPort {
        
        // CODEGEN: Generating message contract since the operation Execute_Report is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HCCSManager.WorkdayHCCS.Execute_ReportOutput Execute_Report(HCCSManager.WorkdayHCCS.Execute_ReportInput request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Execute_ReportType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Report_ParametersType report_ParametersField;
        
        private AuthenticationType authenticationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Report_ParametersType Report_Parameters {
            get {
                return this.report_ParametersField;
            }
            set {
                this.report_ParametersField = value;
                this.RaisePropertyChanged("Report_Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AuthenticationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Report_ParametersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class MgtLevelType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mgtLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MgtLevel {
            get {
                return this.mgtLevelField;
            }
            set {
                this.mgtLevelField = value;
                this.RaisePropertyChanged("MgtLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Management_LevelObjectIDType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Management_LevelObjectType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Management_LevelObjectIDType[] idField;
        
        private string descriptorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID", Order=0)]
        public Management_LevelObjectIDType[] ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
                this.RaisePropertyChanged("Descriptor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Cost_CenterObjectIDType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Cost_CenterObjectType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Cost_CenterObjectIDType[] idField;
        
        private string descriptorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID", Order=0)]
        public Cost_CenterObjectIDType[] ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
                this.RaisePropertyChanged("Descriptor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Unique_IdentifierObjectIDType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Unique_IdentifierObjectType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Unique_IdentifierObjectIDType[] idField;
        
        private string descriptorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID", Order=0)]
        public Unique_IdentifierObjectIDType[] ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
                this.RaisePropertyChanged("Descriptor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class Report_EntryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private Unique_IdentifierObjectType[] workEmailField;
        
        private System.DateTime hireDateField;
        
        private bool hireDateFieldSpecified;
        
        private Cost_CenterObjectType departmentField;
        
        private Management_LevelObjectType managementLevelField;
        
        private string employeeIDField;
        
        private string deptIDField;
        
        private string department11Field;
        
        private string workEmail11Field;
        
        private MgtLevelType mgtLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workEmail", Order=3)]
        public Unique_IdentifierObjectType[] workEmail {
            get {
                return this.workEmailField;
            }
            set {
                this.workEmailField = value;
                this.RaisePropertyChanged("workEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime hireDate {
            get {
                return this.hireDateField;
            }
            set {
                this.hireDateField = value;
                this.RaisePropertyChanged("hireDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hireDateSpecified {
            get {
                return this.hireDateFieldSpecified;
            }
            set {
                this.hireDateFieldSpecified = value;
                this.RaisePropertyChanged("hireDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Cost_CenterObjectType department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Management_LevelObjectType ManagementLevel {
            get {
                return this.managementLevelField;
            }
            set {
                this.managementLevelField = value;
                this.RaisePropertyChanged("ManagementLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DeptID {
            get {
                return this.deptIDField;
            }
            set {
                this.deptIDField = value;
                this.RaisePropertyChanged("DeptID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string department11 {
            get {
                return this.department11Field;
            }
            set {
                this.department11Field = value;
                this.RaisePropertyChanged("department11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string workEmail11 {
            get {
                return this.workEmail11Field;
            }
            set {
                this.workEmail11Field = value;
                this.RaisePropertyChanged("workEmail11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public MgtLevelType MgtLevel {
            get {
                return this.mgtLevelField;
            }
            set {
                this.mgtLevelField = value;
                this.RaisePropertyChanged("MgtLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load")]
    public partial class AuthenticationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string proxy_User_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Proxy_User_Name {
            get {
                return this.proxy_User_NameField;
            }
            set {
                this.proxy_User_NameField = value;
                this.RaisePropertyChanged("Proxy_User_Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute_ReportInput {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load", Order=0)]
        public HCCSManager.WorkdayHCCS.Execute_ReportType Execute_Report;
        
        public Execute_ReportInput() {
        }
        
        public Execute_ReportInput(HCCSManager.WorkdayHCCS.Execute_ReportType Execute_Report) {
            this.Execute_Report = Execute_Report;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute_ReportOutput {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com.workday.report/Lee_Marrette/HCCS_Initial_Load", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Report_Entry", IsNullable=false)]
        public HCCSManager.WorkdayHCCS.Report_EntryType[] Report_Data;
        
        public Execute_ReportOutput() {
        }
        
        public Execute_ReportOutput(HCCSManager.WorkdayHCCS.Report_EntryType[] Report_Data) {
            this.Report_Data = Report_Data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportPortChannel : HCCSManager.WorkdayHCCS.ReportPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportPortClient : System.ServiceModel.ClientBase<HCCSManager.WorkdayHCCS.ReportPort>, HCCSManager.WorkdayHCCS.ReportPort {
        
        public ReportPortClient() {
        }
        
        public ReportPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HCCSManager.WorkdayHCCS.Execute_ReportOutput HCCSManager.WorkdayHCCS.ReportPort.Execute_Report(HCCSManager.WorkdayHCCS.Execute_ReportInput request) {
            return base.Channel.Execute_Report(request);
        }
        
        public HCCSManager.WorkdayHCCS.Report_EntryType[] Execute_Report(HCCSManager.WorkdayHCCS.Execute_ReportType Execute_Report1) {
            HCCSManager.WorkdayHCCS.Execute_ReportInput inValue = new HCCSManager.WorkdayHCCS.Execute_ReportInput();
            inValue.Execute_Report = Execute_Report1;
            HCCSManager.WorkdayHCCS.Execute_ReportOutput retVal = ((HCCSManager.WorkdayHCCS.ReportPort)(this)).Execute_Report(inValue);
            return retVal.Report_Data;
        }
    }
}
